# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=255)),
                ('phone_number', models.TextField(default='', max_length=15)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='phonebook.Book')),
            ],
        ),
    ]
